// Generated by gencpp from file rosjava_custom_srv/CustomService2.msg
// DO NOT EDIT!


#ifndef ROSJAVA_CUSTOM_SRV_MESSAGE_CUSTOMSERVICE2_H
#define ROSJAVA_CUSTOM_SRV_MESSAGE_CUSTOMSERVICE2_H

#include <ros/service_traits.h>


#include <rosjava_custom_srv/CustomService2Request.h>
#include <rosjava_custom_srv/CustomService2Response.h>


namespace rosjava_custom_srv
{

struct CustomService2
{

typedef CustomService2Request Request;
typedef CustomService2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CustomService2
} // namespace rosjava_custom_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosjava_custom_srv::CustomService2 > {
  static const char* value()
  {
    return "f0b6d69ea10b0cf210cb349d58d59e8f";
  }

  static const char* value(const ::rosjava_custom_srv::CustomService2&) { return value(); }
};

template<>
struct DataType< ::rosjava_custom_srv::CustomService2 > {
  static const char* value()
  {
    return "rosjava_custom_srv/CustomService2";
  }

  static const char* value(const ::rosjava_custom_srv::CustomService2&) { return value(); }
};


// service_traits::MD5Sum< ::rosjava_custom_srv::CustomService2Request> should match 
// service_traits::MD5Sum< ::rosjava_custom_srv::CustomService2 > 
template<>
struct MD5Sum< ::rosjava_custom_srv::CustomService2Request>
{
  static const char* value()
  {
    return MD5Sum< ::rosjava_custom_srv::CustomService2 >::value();
  }
  static const char* value(const ::rosjava_custom_srv::CustomService2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosjava_custom_srv::CustomService2Request> should match 
// service_traits::DataType< ::rosjava_custom_srv::CustomService2 > 
template<>
struct DataType< ::rosjava_custom_srv::CustomService2Request>
{
  static const char* value()
  {
    return DataType< ::rosjava_custom_srv::CustomService2 >::value();
  }
  static const char* value(const ::rosjava_custom_srv::CustomService2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosjava_custom_srv::CustomService2Response> should match 
// service_traits::MD5Sum< ::rosjava_custom_srv::CustomService2 > 
template<>
struct MD5Sum< ::rosjava_custom_srv::CustomService2Response>
{
  static const char* value()
  {
    return MD5Sum< ::rosjava_custom_srv::CustomService2 >::value();
  }
  static const char* value(const ::rosjava_custom_srv::CustomService2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosjava_custom_srv::CustomService2Response> should match 
// service_traits::DataType< ::rosjava_custom_srv::CustomService2 > 
template<>
struct DataType< ::rosjava_custom_srv::CustomService2Response>
{
  static const char* value()
  {
    return DataType< ::rosjava_custom_srv::CustomService2 >::value();
  }
  static const char* value(const ::rosjava_custom_srv::CustomService2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSJAVA_CUSTOM_SRV_MESSAGE_CUSTOMSERVICE2_H
