(cl:defpackage rosjava_custom_srv-srv
  (:use )
  (:export
   "CUSTOMSERVICE"
   "<CUSTOMSERVICE-REQUEST>"
   "CUSTOMSERVICE-REQUEST"
   "<CUSTOMSERVICE-RESPONSE>"
   "CUSTOMSERVICE-RESPONSE"
   "CUSTOMSERVICE1"
   "<CUSTOMSERVICE1-REQUEST>"
   "CUSTOMSERVICE1-REQUEST"
   "<CUSTOMSERVICE1-RESPONSE>"
   "CUSTOMSERVICE1-RESPONSE"
   "CUSTOMSERVICE2"
   "<CUSTOMSERVICE2-REQUEST>"
   "CUSTOMSERVICE2-REQUEST"
   "<CUSTOMSERVICE2-RESPONSE>"
   "CUSTOMSERVICE2-RESPONSE"
  ))

